// src/utils/pdfGenerator.js
import jsPDF from 'jspdf'

export const downloadWorkoutPDF = (workoutData) => {
  const doc = new jsPDF()

  const accentColor = [14, 165, 233] // #0ea5e9
  const darkColor = [51, 51, 51]
  const lightGray = [245, 245, 245]
  const borderGray = [221, 221, 221]

  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // ── Title ───────────────────────────────────────────────
  doc.setFontSize(22)
  doc.setTextColor(...accentColor)
  doc.setFont('helvetica', 'bold')
  doc.text('Weekly Workout Plan', pageWidth / 2, y, { align: 'center' })
  y += 12

  doc.setDrawColor(...accentColor)
  doc.setLineWidth(0.5)
  doc.line(20, y, pageWidth - 20, y)
  y += 10

  // ── Days ─────────────────────────────────────────────────
  workoutData.forEach((day) => {
    const exerciseCount = day.exercises?.length || 0
    const blockHeight = 14 + exerciseCount * 10 + 8

    // Add new page if not enough space
    if (y + blockHeight > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage()
      y = 20
    }

    // Day card background
    doc.setFillColor(...lightGray)
    doc.setDrawColor(...borderGray)
    doc.setLineWidth(0.3)
    doc.roundedRect(15, y, pageWidth - 30, blockHeight, 3, 3, 'FD')

    // Left accent bar
    doc.setFillColor(...accentColor)
    doc.roundedRect(15, y, 4, blockHeight, 2, 2, 'F')

    // Day title
    doc.setFontSize(13)
    doc.setTextColor(...accentColor)
    doc.setFont('helvetica', 'bold')
    doc.text(day.day, 24, y + 9)

    y += 14

    // Exercises
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...darkColor)

    if (exerciseCount === 0) {
      doc.text('No exercises', 24, y)
      y += 10
    } else {
      day.exercises.forEach((ex) => {
        doc.text(`• ${ex.name}`, 24, y)
        doc.setTextColor(120, 120, 120)
        doc.text(ex.sets, pageWidth - 25, y, { align: 'right' })
        doc.setTextColor(...darkColor)
        y += 9
      })
    }

    y += 20
  })

  // ── Footer ───────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor(180, 180, 180)
    doc.text(
      `Generated by FitAI • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  doc.save('FitAI-Workout-Plan.pdf')
}